packages:
  - packages/*
  - demo/*
  - slides/*

catalog:
  prettier: 3.8.1
  prettier-plugin-slidev: 1.0.5
  redis: 5.11.0

catalogs:
  slidev:
    '@slidev/cli': 52.14.1
    playwright-chromium: 1.58.2
    slidev-theme-academic: 2.1.0
    vue: 3.5.30

onlyBuiltDependencies:
  - esbuild
  - nx
  - playwright-chromium
