name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release:
        description: Release
        required: false
        default: false
        type: boolean

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          cache: true

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .tool-versions
          cache: pnpm

      - name: Derive SHAs for Nx Affected
        id: set-shas
        uses: nrwl/nx-set-shas@v4

      - name: Install Node Dependencies
        run: pnpm install

      - name: Playwright Install
        run: npx playwright install chromium --with-deps

      - name: Setup Git User
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions [Bot]"

      - name: Run Nx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm nx affected \
            --target=build \
            --target=export \
            --target=deploy \
            --parallel \
            --configuration=ci \
            --max-parallel=3

      - uses: actions/upload-artifact@v4
        with:
          name: slides
          path: dist/release/

      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event.inputs.release == 'true' }}
        with:
          files: dist/release/*
          tag_name: v${{ github.run_number }}
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
